name = "IntCombOpt567"
uuid = "6bd204e6-ad69-4d94-9a7a-38613e34ad7e"
authors = ["Aryan Ritwajeet Jha <aryan.r.jha@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
